### ISSUE TITLE
[Feature Request] API that returns artwork information from artwork ID

### ISSUE THREAD

**Issue by seriaati** [HazelTheWitch/phixiv#11]
# What?
A simple GET API that fetches artwork information from artwork ID.
## Return what?
- Number of images associated with this artwork ID. (int)
- Artist name (str)
- Artwork tags (list of str)
- Number of likes (int)
# Why?
If an artwork contains multiple images, using `/d/<artwork_id>` only returns the original image of the first image of the artwork. If the API mentioned above exists, I don't have to iterate through `/d/<artwork_id>/<index>` with an increasing number while catching for the invalid request exception. The other data is just some info that I think would be useful.

**Comment by HazelTheWitch** [comment]
I added the API, it lives at `www.phixiv.net/api/info` query parameters are id and optionally language. I removed direct image links because this API essentially does what it did but better. This should be much faster and more efficient for everyone involved. It includes title, description, tags in whatever language you requested, author info, and image URLs.
